apiVersion: v1
kind: Service
metadata:
  name: paymybuddy-backend
spec:
  selector:
    app: paymybuddy-backend
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31010  # Port accessible depuis l'extérieur
  type: NodePort
